### ISSUE TITLE
Missing FONT URW Sans create Crash KR-07.

### ISSUE THREAD

**Issue by nschulux** [bluewaysw/pcgeos#244] opened 2023-10-18 19:54 UTC
System Crash by opening Help and by opening document helpsource with write if missing font URW SANS.

Should be set default font berkley.fnt in system also for help and write and others. 
![Hilfe URW Sans](https://github.com/bluewaysw/pcgeos/assets/118665816/c76a66b9-8517-40f5-81a7-37df96c7dc33)
![Helsource Freegeos](https://github.com/bluewaysw/pcgeos/assets/118665816/b956ce9a-1ce4-4c14-a57d-4bf7ec1a5226)

**Comment by mgroeber9110** [comment] 2023-10-22 16:20
Here is a quick analysis of what seems to be happening:

- The crash is due to an invalid stack frame in the ´TextCallDriver´ kernel function (`Library\Kernel\Graphics\graphicsText.asm`) which is part of the `GrDrawTextField` implementation.
- It occurs after drawing a hyperlink (because of the underlined text style).
- The problem is that the function pushes 3 additional words on the stack if any `KERNEL_STYLES` are set in `ds:GS_fontAttr.FCA_textStyle`, and tries to remove them before returing. However, in case a non-installed font is used (e.g. URW Sans), the call to `LockWinFont' changes `GS_fontAttr` to point to the default font (Berkeley) and zeroes `FCA_textStyle`.
- As a result, the 3 words are pushed before locking the font, but the stack is not adjusted correctly when returning.

As the function appears to have several entry points and a number of alternative code path, the fix requires a bit more analysis.

**Comment by hanslse** [comment] 2023-11-19 15:00
Can confirm nschulux observation, I get the same error in the English version of the pcgeos-ensemble_nc.zip, downloaded today, 11-19-2023.

**Comment by bluewaysw** [comment] 2023-11-25 22:03
It looks like this is a general issue one a font substitution needs to happen (original font is not available), then the kernel styles become removed when storing available styles from the choosen font. Because kernel style are font independent a fix could just keep the kernel styles and every thing should be fine.

**Comment by bluewaysw** [comment] 2023-11-26 14:17
Fix merged to master.

**Closed by bluewaysw** 2023-11-26 14:17 UTC
